### ISSUE TITLE
[Documentation] Document Structure of ExtraInfo Objects

### ISSUE THREAD

**Issue by fril-soptim** [SOPTIM/cgmes2pgm_converter#3]
The Converter creates an `ExtraInfo` object that links elements in the PGM dataset with corresponding objects in the CGMES dataset. It also provides additional metadata, such as its name and the substation an element belongs to.

The contents of the `ExtraInfo` object depend on the type of the element. For example, each branch includes references to both of its terminals. Transformers include further attributes, such as electrical parameters extracted from the CGMES dataset.

The available attributes for each element type must be clearly documented.

## Example

`ExtraInfo` of a transformer:

```yaml
{
  "_type": "PowerTransformer-2W",
  "_name": "transformer-name", 
  "_term1": "http://localhost:3030/dataset/data#_uuid", 
  "_term2": "http://localhost:3030/dataset/data#_uuid", 
  "_mrid": "http://localhost:3030/dataset/data#_uuid",
  "_r": 0.0, 
  "_x": 18.6824, 
  "_g": 0, 
  "_b": 0.0, 
  "_sn": 300000000.0
}
```
